heimdall:
  node:
    id: primary-0
    role: PRIMARY
    replicas:
      - id: primary-0-replica-0
        base-url: http://primary-0-replica-0:8081
      - id: primary-0-replica-1
        base-url: http://primary-0-replica-1:8081
